#!/usr/bin/env python3
"""Builds /tmp/export/arpg_cards_and_passives.xlsx (Cards + Character Passives tabs)
from the game data dump. Google Sheets imports it directly.

Usage:
  godot --headless --path . --script tests/dump_game_data.gd
  python3 tests/build_cards_spreadsheet.py
"""
import json, re, zipfile, os, csv, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
data = json.load(open("/tmp/game_data.json"))
cards = data["cards"]
trees = data["skill_trees"]
chars = data["characters"]

card_src = open(f"{ROOT}/scripts/cards/card.gd").read()
main_src = open(f"{ROOT}/scripts/core/main.gd").read()

# ---------- 1. Wiring sets ----------
def match_arms(block: str) -> set:
    """Card ids appearing as match arms ("a": / "a", "b":) inside a block."""
    ids = set()
    for line in block.splitlines():
        m = re.match(r'^\t+((?:"[a-z_0-9]+"\s*,\s*)*"[a-z_0-9]+")\s*:\s*(#.*)?$', line)
        if m:
            ids.update(re.findall(r'"([a-z_0-9]+)"', m.group(1)))
    return ids

# card.gd execute() match: from first 'match card_id:' to its default arm '_:'
exec_block = card_src.split("match card_id:", 1)[1]
exec_block = exec_block[: exec_block.index("\n\t\t_:")]
exec_arms = match_arms(exec_block)

# main.gd _apply_card_world_effects match
we = main_src.split("func _apply_card_world_effects", 1)[1]
we = we[: re.search(r"\nfunc ", we).start()]
world_arms = match_arms(we)

# scattered special-case checks across all scripts
scattered = set()
for dirpath, _, files in os.walk(f"{ROOT}/scripts"):
    for fn in files:
        if fn.endswith(".gd"):
            txt = open(os.path.join(dirpath, fn)).read()
            scattered.update(re.findall(r'card_id [!=]= "([a-z_0-9]+)"', txt))

wired_ids = exec_arms | world_arms | scattered
wired_ids.add("basic_attack")  # resolved via is_basic_attack flag in main.gd queue

# ---------- 2. Ownership from card.gd sections ----------
section_owner = [
    ("# Factory methods", "Common"),
    ("# BRAD CARD FACTORY METHODS", "Brad"),
    ("# JEREMY CARD FACTORY METHODS", "Jeremy"),
    ("# RYAN CARD FACTORY METHODS", "Ryan"),
    ("# STEPHEN CARD FACTORY METHODS", "Stephen"),
    ("# CORY CARD FACTORY METHODS", "Cory"),
    ("# === Reaction / Unplayable / On Draw Cards ===", "Common"),
    ("# POWER CARDS (Maintain keyword)", "Common"),
    ("# JEREMY GENERATED CARDS", "Jeremy"),
]
sec_positions = sorted(
    [(card_src.index(h), o) for h, o in section_owner if h in card_src]
)
factory_owner = {}
for m in re.finditer(r"static func (create_[a-z_0-9]+)", card_src):
    owner = "Common"
    for pos, o in sec_positions:
        if pos < m.start():
            owner = o
    factory_owner[m.group(1)] = owner

# ---------- 3. Skill tree maps ----------
tree_card_map = {}   # card_id -> (char, level)
passive_rows = []    # passives tab
for cname, rows in trees.items():
    for r in rows:
        if r["type"] == "Card" and r["card_id"]:
            tree_card_map.setdefault(r["card_id"], (cname, r["level"]))
        elif r["type"] in ("Passive", "Mutation"):
            desc = r["description"]
            arch = ""
            m = re.match(re.escape(r["name"]) + r" \((.+?)\): (.*)$", desc, re.S)
            if m:
                arch, desc = m.group(1), m.group(2)
            passive_rows.append({
                "char": cname, "arch": arch, "level": r["level"],
                "name": r["name"], "desc": desc, "source": "Skill tree option",
            })
# Innate character passives
for c in chars:
    passive_rows.append({
        "char": c["name"], "arch": "—", "level": 1,
        "name": "Innate Passive", "desc": c["passive_description"],
        "source": "Innate (character select)",
    })
passive_rows.sort(key=lambda p: (p["char"], p["level"], p["name"]))

# ---------- 4. Sources ----------
start_deck = collections.defaultdict(list)  # card_id -> [chars]
for c in chars:
    for cid in set(c["starting_card_ids"]):
        start_deck[cid].append(c["name"])

dungeon_src = open(f"{ROOT}/scripts/core/dungeon_manager.gd").read()
chest_pool = {f[len("create_"):] for f in re.findall(r"Card\.(create_[a-z_0-9]+)", dungeon_src)}
spawner_src = open(f"{ROOT}/scripts/battle/enemy_spawner.gd").read()
enemy_pool = {f[len("create_"):] for f in re.findall(r"Card\.(create_[a-z_0-9]+)", spawner_src)}

quest_src = open(f"{ROOT}/scripts/character/questionnaire_data.gd").read()
quest_ids = set(re.findall(r'"([a-z_0-9]+)",', quest_src))
starting_items = {
    "healing_potion": "Starting item (Ryan — Adventurer's Belt)",
    "dagger_throw": "Starting item (Ryan — Adventurer's Belt)",
    "blink": "Starting item (Stephen — Flickerstep Boots)",
}
generated = {
    "shuriken": ("Ryan", "Generated by Shuriken Pouch (Manifest)"),
    "quick_arrow": ("Stephen", "Generated by Enchanted Quiver"),
    "biscuit": ("Jeremy", "Generated by Risk It (30% chance)"),
    "energy_ball": ("Cory", "Generated by Absorb Essence"),
    "energy_barrier": ("Cory", "Generated by Energy Barrier passive"),
    "mana_surge": ("Jeremy", "Generated by Mana Surge passive"),
    "magic_barrier": ("Jeremy", "Generated by A Mage's Favor passive"),
    "shepherds_mark": ("Jeremy", "Generated by Whispers of the Flock passive"),
    "savage_strike_copy": ("Brad", "Generated by Savage Strike"),
    "minor_wounds": (None, "Generated by Reckless Strike"),
    "lightly_dazed": (None, "Status applied by enemies"),
    "basic_attack": (None, "Generated by free-attack procs"),
    "gulped_potion": (None, "Granted by items"),
    "potion_of_continuance": (None, "Granted by items"),
}

# Basic Attack (parameterized factory excluded from runtime dump) — pull costs from source
ba = re.search(r"static func create_basic_attack.*?return card", card_src, re.S).group(0)
ba_mana = int(re.search(r"mana_cost = (\d+)", ba).group(1)) if re.search(r"mana_cost = (\d+)", ba) else 0
ba_tempo = int(re.search(r"tempo_cost = (\d+)", ba).group(1)) if re.search(r"tempo_cost = (\d+)", ba) else 0
cards.append({
    "factory": "create_basic_attack", "card_id": "basic_attack", "card_name": "Basic Attack",
    "description": "Free basic attack generated by passives and procs (damage set when created)",
    "type": "Attack", "mana_cost": ba_mana, "tempo_cost": ba_tempo,
    "in_hand_buff": "", "has_on_draw": False,
})

# ---------- 5. Assemble card rows ----------
def wired_label(c):
    cid = c["card_id"]
    if c["type"] == "Unplayable":
        return "N/A (unplayable status card)"
    if cid in wired_ids:
        return "Yes"
    if c.get("in_hand_buff"):
        return "Yes (in-hand effect)"
    return "No"

card_rows = []
mismatches = [cid for cid in tree_card_map if cid not in {c["card_id"] for c in cards}]
for c in cards:
    cid = c["card_id"]
    owner = factory_owner.get(c["factory"], "Common")
    if cid in tree_card_map:
        owner = tree_card_map[cid][0]
    elif cid in generated and generated[cid][0]:
        owner = generated[cid][0]

    in_tree = "No"
    if cid in tree_card_map:
        tc, lv = tree_card_map[cid]
        in_tree = f"Yes — Lv {lv} ({tc})"

    src = []
    if cid in start_deck:
        who = start_deck[cid]
        src.append("Starting deck (all characters)" if len(who) == 5 else f"Starting deck ({', '.join(sorted(who))})")
    if cid in starting_items:
        src.append(starting_items[cid])
    if cid in tree_card_map:
        src.append(f"Skill tree ({tree_card_map[cid][0]} Lv {tree_card_map[cid][1]})")
    if cid in chest_pool:
        src.append("Chest loot pool")
    if cid in enemy_pool:
        src.append("Enemy loot pool")
    if cid in quest_ids and cid not in start_deck:
        src.append("Questionnaire character starting deck")
    if cid in generated:
        src.append(generated[cid][1])
    if not src:
        src.append("Town card shop only")

    card_rows.append({
        "name": c["card_name"], "id": cid, "owner": owner, "type": c["type"],
        "desc": c["description"], "mana": c["mana_cost"], "tempo": c["tempo_cost"],
        "wired": wired_label(c), "tree": in_tree, "src": "; ".join(src),
    })

owner_order = {"Common": 0, "Brad": 1, "Cory": 2, "Jeremy": 3, "Ryan": 4, "Stephen": 5}
card_rows.sort(key=lambda r: (owner_order.get(r["owner"], 9), r["name"]))

# ---------- 6. Write XLSX ----------
def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))

def cell(ref, val, style=0):
    if isinstance(val, (int, float)) and not isinstance(val, bool):
        return f'<c r="{ref}" s="{style}"><v>{val}</v></c>'
    return f'<c r="{ref}" t="inlineStr" s="{style}"><is><t xml:space="preserve">{esc(val)}</t></is></c>'

def col_letter(i):
    s = ""
    while i >= 0:
        s = chr(65 + i % 26) + s
        i = i // 26 - 1
    return s

def sheet_xml(headers, widths, rows):
    n_rows, n_cols = len(rows) + 1, len(headers)
    cols = "".join(
        f'<col min="{i+1}" max="{i+1}" width="{w}" customWidth="1"/>' for i, w in enumerate(widths)
    )
    out = [
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">',
        '<sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews>',
        f"<cols>{cols}</cols><sheetData>",
        '<row r="1">' + "".join(cell(f"{col_letter(i)}1", h, 1) for i, h in enumerate(headers)) + "</row>",
    ]
    for ri, row in enumerate(rows, start=2):
        out.append(
            f'<row r="{ri}">' + "".join(
                cell(f"{col_letter(ci)}{ri}", v, 2 if isinstance(v, str) else 0)
                for ci, v in enumerate(row)
            ) + "</row>"
        )
    out.append(f'</sheetData><autoFilter ref="A1:{col_letter(n_cols-1)}{n_rows}"/></worksheet>')
    return "".join(out)

cards_sheet = sheet_xml(
    ["Card Name", "Card ID", "Owner", "Type", "Description", "Mana Cost", "Tempo Cost",
     "Wired In", "In Skill Tree", "Sources (all cards also sold in town card shop)"],
    [22, 20, 10, 12, 60, 10, 10, 24, 20, 46],
    [[r["name"], r["id"], r["owner"], r["type"], r["desc"], r["mana"], r["tempo"],
      r["wired"], r["tree"], r["src"]] for r in card_rows],
)
pass_sheet = sheet_xml(
    ["Character", "Archetype", "Level", "Passive Name", "Description", "Source"],
    [12, 18, 8, 24, 85, 24],
    [[p["char"], p["arch"], p["level"], p["name"], p["desc"], p["source"]] for p in passive_rows],
)

styles = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
    '<fonts count="2"><font><sz val="11"/><name val="Calibri"/></font>'
    '<font><b/><sz val="11"/><name val="Calibri"/></font></fonts>'
    '<fills count="2"><fill><patternFill patternType="none"/></fill>'
    '<fill><patternFill patternType="gray125"/></fill></fills>'
    '<borders count="1"><border/></borders>'
    '<cellStyleXfs count="1"><xf/></cellStyleXfs>'
    '<cellXfs count="3"><xf/><xf fontId="1" applyFont="1"/>'
    '<xf applyAlignment="1"><alignment wrapText="1" vertical="top"/></xf></cellXfs>'
    "</styleSheet>"
)
workbook = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
    'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
    '<sheets><sheet name="Cards" sheetId="1" r:id="rId1"/>'
    '<sheet name="Character Passives" sheetId="2" r:id="rId2"/></sheets></workbook>'
)
wb_rels = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'
    '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/>'
    '<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'
    "</Relationships>"
)
root_rels = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
    "</Relationships>"
)
content_types = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
    '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
    '<Default Extension="xml" ContentType="application/xml"/>'
    '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
    '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
    '<Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
    '<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
    "</Types>"
)

os.makedirs("/tmp/export", exist_ok=True)
xlsx_path = "/tmp/export/arpg_cards_and_passives.xlsx"
with zipfile.ZipFile(xlsx_path, "w", zipfile.ZIP_DEFLATED) as z:
    z.writestr("[Content_Types].xml", content_types)
    z.writestr("_rels/.rels", root_rels)
    z.writestr("xl/workbook.xml", workbook)
    z.writestr("xl/_rels/workbook.xml.rels", wb_rels)
    z.writestr("xl/styles.xml", styles)
    z.writestr("xl/worksheets/sheet1.xml", cards_sheet)
    z.writestr("xl/worksheets/sheet2.xml", pass_sheet)

# CSV fallbacks
with open("/tmp/export/cards.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["Card Name", "Card ID", "Owner", "Type", "Description", "Mana Cost",
                "Tempo Cost", "Wired In", "In Skill Tree", "Sources"])
    for r in card_rows:
        w.writerow([r["name"], r["id"], r["owner"], r["type"], r["desc"], r["mana"],
                    r["tempo"], r["wired"], r["tree"], r["src"]])
with open("/tmp/export/character_passives.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["Character", "Archetype", "Level", "Passive Name", "Description", "Source"])
    for p in passive_rows:
        w.writerow([p["char"], p["arch"], p["level"], p["name"], p["desc"], p["source"]])

# ---------- 7. Report ----------
wc = collections.Counter(r["wired"] for r in card_rows)
oc = collections.Counter(r["owner"] for r in card_rows)
pc = collections.Counter(p["char"] for p in passive_rows)
print("CARDS:", len(card_rows), dict(oc))
print("WIRED:", dict(wc))
print("NOT WIRED:", sorted(r["id"] for r in card_rows if r["wired"] == "No"))
print("PASSIVES:", len(passive_rows), dict(pc))
print("TREE CARD IDS WITHOUT FACTORY:", mismatches)
print("XLSX:", xlsx_path, os.path.getsize(xlsx_path), "bytes")
