#!/usr/bin/env python3
"""Writes the stored-build sweeps for one character from its component
library (tests/sim/builds/<character>_builds.gd, names via sim_out/catalog.json).

  godot --headless --path . --script tests/sim/dump_catalog.gd
  python3 tools/sim_analysis/gen_build_sweeps.py --character ryan [--level 18] [--seeds 100]
        [--enemies LARGE_BEAR,TREANT,...] [--enemy-scale hp:1.5,dmg:1.3]

Sweeps (run with tests/sim/run_sim.gd --sweep=<file> or run_sweep.sh):
  <char>_designed.txt       every designed build x the enemy set
  <char>_items_x_decks.txt  every item set x every deck, with the item set's own stats/sphere/passives
  <char>_alloc_x_sphere.txt every allocation x every sphere path, on each designed build
  <char>_passives.txt       every passive set on each designed build
  <char>_passive_focus.txt  every tree passive maxed (rank 15) on each designed build, the rest spread
Every job runs through tests/sim/scenarios/build.gd with parts=...; the
sweep file is <char>_<kind>[_L<level>].txt (level 18 untagged); scenario folder is <char>_<build>_e_<ENEMY>[__L_<level>][__k_<component>...]
so build_matrix.py can pivot on any component.
"""
import argparse, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SCEN = "tests/sim/scenarios/build.gd"
DEFAULT_ENEMIES = "LARGE_BEAR,TREANT,BUGBEAR,EARTH_MAGE,WYVERN,ICE_TROLL"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--character", default="ryan")
    ap.add_argument("--level", type=int, default=18)
    ap.add_argument("--catalog", default=os.path.join(ROOT, "sim_out", "catalog.json"))
    ap.add_argument("--out", default=os.path.join(ROOT, "tests", "sim", "sweeps"))
    ap.add_argument("--seeds", type=int, default=100)
    ap.add_argument("--enemies", default=DEFAULT_ENEMIES)
    ap.add_argument("--matrix-enemies", default="LARGE_BEAR,EARTH_MAGE,WYVERN", help="enemies for the mix-and-match matrices")
    ap.add_argument("--enemy-scale", default="", help="hp:x,dmg:y multipliers on every enemy (end-game scaling)")
    args = ap.parse_args()
    char = args.character.lower()
    comp = json.load(open(args.catalog))["builds"][char]
    designed = comp["designed_parts"]
    seeds = "seeds=1-%d" % args.seeds
    enemies = args.enemies.split(",")
    m_enemies = args.matrix_enemies.split(",")
    level_tag = "" if args.level == 18 else "__L_%d" % args.level
    scale = (" enemy_scale=%s" % args.enemy_scale) if args.enemy_scale else ""

    file_tag = "" if args.level == 18 else "_L%d" % args.level

    def write(name, lines, note):
        name = name.replace(".txt", file_tag + ".txt")
        path = os.path.join(args.out, name)
        with open(path, "w") as f:
            f.write("# %s\n# generated by tools/sim_analysis/gen_build_sweeps.py --character %s --level %d; %d job(s)\n" % (note, char, args.level, len(lines)))
            f.write("\n".join(lines) + "\n")
        runs = len(lines) * args.seeds
        print("%-28s %5d jobs %7d runs (~%.1f h at 1.5 s/run on one core) -> %s" % (name, len(lines), runs, runs * 1.5 / 3600, os.path.relpath(path, ROOT)))

    def job(build, enemy, parts, tag):
        p = dict(parts); p["character"] = char; p["build"] = build; p["level"] = args.level
        ps = ",".join("%s:%s" % kv for kv in p.items())
        return "scenario=%s enemy=%s%s parts=%s name=e_%s%s%s %s" % (SCEN, enemy, scale, ps, enemy, level_tag, tag, seeds)

    write("%s_designed.txt" % char, [job(b, e, {}, "") for b in designed for e in enemies], "%s designed builds x enemies" % char)

    lines = []
    for items in comp["items"]:
        owner = next((b for b, d in designed.items() if d["items"] == items), list(designed)[0])
        for deck in comp["deck"]:
            for e in m_enemies:
                lines.append(job(owner, e, {"items": items, "deck": deck}, "__i_%s__d_%s" % (items, deck)))
    write("%s_items_x_decks.txt" % char, lines, "%s item set x deck (stats, sphere and passives of the item set's archetype)" % char)

    lines = []
    for b in designed:
        for alloc in comp["alloc"]:
            for sphere in comp["sphere"]:
                for e in m_enemies:
                    lines.append(job(b, e, {"alloc": alloc, "sphere": sphere}, "__a_%s__s_%s" % (alloc, sphere)))
    write("%s_alloc_x_sphere.txt" % char, lines, "%s allocation x sphere path on each designed build" % char)

    lines = []
    for b in designed:
        for ps in comp["passives"]:
            for e in m_enemies:
                lines.append(job(b, e, {"passives": ps}, "__p_%s" % ps))
    write("%s_passives.txt" % char, lines, "%s passive sets on each designed build" % char)

    lines = []
    for b in designed:
        for f in comp.get("tree_passives", []):
            for e in m_enemies:
                lines.append(job(b, e, {"focus": f}, "__f_%s" % f.replace("'", "")))
    write("%s_passive_focus.txt" % char, lines, "%s each tree passive maxed (rank 15), remaining points spread over the build's set" % char)


if __name__ == "__main__":
    main()
