#!/usr/bin/env python3
"""Writes the Ryan build sweeps from the component library
(tests/sim/scenarios/ryan/ryan_builds.gd, names via sim_out/catalog.json).

  godot --headless --path . --script tests/sim/dump_catalog.gd
  python3 tools/sim_analysis/gen_ryan_sweeps.py [--seeds 100] [--enemies LARGE_BEAR,TREANT,...]

Sweeps (run with tests/sim/run_sim.gd --sweep=<file> or run_sweep.sh):
  ryan_designed.txt     the six designed builds x the enemy set
  ryan_items_x_decks.txt every item set x every deck, with the item set's own stats/sphere/passives
  ryan_alloc_x_sphere.txt every allocation x every sphere path, on each designed build's gear and deck
  ryan_passives.txt     every passive set on each designed build
Scenario folders are named ryan_<build>_e_<ENEMY>__k_<component>... so
ryan_builds.py can pivot on any component.
"""
import argparse, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SCEN = "tests/sim/scenarios/ryan/%s.gd"
DEFAULT_ENEMIES = "LARGE_BEAR,TREANT,BUGBEAR,EARTH_MAGE,WYVERN,ICE_TROLL"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", default=os.path.join(ROOT, "sim_out", "catalog.json"))
    ap.add_argument("--out", default=os.path.join(ROOT, "tests", "sim", "sweeps"))
    ap.add_argument("--seeds", type=int, default=100)
    ap.add_argument("--enemies", default=DEFAULT_ENEMIES)
    ap.add_argument("--matrix-enemies", default="LARGE_BEAR,EARTH_MAGE,WYVERN", help="enemies for the mix-and-match matrices")
    args = ap.parse_args()
    comp = json.load(open(args.catalog))["ryan_components"]
    designed = comp["designed_parts"]
    seeds = "seeds=1-%d" % args.seeds
    enemies = args.enemies.split(",")
    m_enemies = args.matrix_enemies.split(",")

    def write(name, lines, note):
        path = os.path.join(args.out, name)
        with open(path, "w") as f:
            f.write("# %s\n# generated by tools/sim_analysis/gen_ryan_sweeps.py; %d job(s)\n" % (note, len(lines)))
            f.write("\n".join(lines) + "\n")
        runs = len(lines) * args.seeds
        print("%-24s %5d jobs %7d runs (~%.1f h at 0.5 s/run) -> %s" % (name, len(lines), runs, runs * 0.5 / 3600, os.path.relpath(path, ROOT)))

    def job(build, enemy, parts, tag):
        p = ",".join("%s:%s" % kv for kv in parts.items())
        return "scenario=%s enemy=%s parts=%s name=e_%s%s %s" % (SCEN % build, enemy, p, enemy, tag, seeds)

    lines = [job(b, e, {}, "") for b in designed for e in enemies]
    write("ryan_designed.txt", lines, "Ryan designed builds x enemies")

    lines = []
    for items in comp["items"]:
        owner = next(b for b, d in designed.items() if d["items"] == items)
        for deck in comp["deck"]:
            for e in m_enemies:
                lines.append(job(owner, e, {"items": items, "deck": deck}, "__i_%s__d_%s" % (items, deck)))
    write("ryan_items_x_decks.txt", lines, "Ryan item set x deck (stats, sphere and passives of the item set's archetype)")

    lines = []
    for b in designed:
        for alloc in comp["alloc"]:
            for sphere in comp["sphere"]:
                for e in m_enemies:
                    lines.append(job(b, e, {"alloc": alloc, "sphere": sphere}, "__a_%s__s_%s" % (alloc, sphere)))
    write("ryan_alloc_x_sphere.txt", lines, "Ryan allocation x sphere path on each designed build")

    lines = []
    for b in designed:
        for ps in comp["passives"]:
            for e in m_enemies:
                lines.append(job(b, e, {"passives": ps}, "__p_%s" % ps))
    write("ryan_passives.txt", lines, "Ryan passive sets on each designed build")


if __name__ == "__main__":
    main()
